individual ID column is now optional
qiime2/q2-longitudinal pull request #104
Opened 2018-06-29 21:12 UTC by nbokulich

fixes #103 

@thermokarst this seems to work (I can supply manual testing examples if needed) but I will need your review since I am really just taking to that vega spec like an amateur surgeon. 🔪🍝 

Please let me know if there are additional tests needed — it looks like all the tests you put in previously are mostly "does it run" tests... I assume it would error if vega encountered an invalid spec. These changes do not really require any "input validation" type tests.

2018-07-05 21:54 UTC, nbokulich commented
note: looks like these changes cause line plots to be displayed, but not individual points colored by group.

2018-07-06 16:05 UTC, thermokarst requested changes
Pulled this critter down and put it through the paces - good work spaghetti-surgeon @nbokulich! I have one minor test request, inline. Thanks!

2018-07-06 16:05 UTC, thermokarst commented on q2_longitudinal/tests/test_longitudinal.py
> +    def test_volatility_no_individual_id_column(self):
This PR gets us in the business of conditionally rendering the vega spec - how about we do a check in this test to make sure that the portions of the spec we expect to be missing are in fact gone now. For example, you could ensure that the substring `spaghettiLine` isn't present (I think - you should double check me on that).

2018-07-09 15:12 UTC, nbokulich commented
thanks @thermokarst ! I have modified 2 tests to confirm that the spaghetti maker is working as intended when individual id column is (not) passed! Let me know if you had something else in mind.

2018-07-09 16:24 UTC, thermokarst approved these changes

2018-07-09 16:24 UTC, merged