Issue 32
qiime2/q2-longitudinal pull request #36
Opened 2017-09-08 15:41 UTC by nbokulich

fixes #32 
fixes #35 

Well, it's a partial fix to #32 , but enough to close that issue. I added control charts, but instead of using the qiime1 volatility analysis I use tests for equality of variance to examine volatility and data spread across time. LME, already in `q2-longitudinal`, appears to be a better way to examine differences in longitudinal trajectory than the qiime1 volatility methods. So I don't plan to implement the qiime1 methods and we can close #32.

2017-09-08 18:38 UTC, nbokulich commented
@thermokarst I just requested @gregcaporaso as a secondary reviewer — he and I had already discussed this visualizer a little bit; and since this is a whole new action I'm adding, it's a bit of a big PR. Thanks guys!

2017-09-08 19:09 UTC, thermokarst requested changes
Thanks @nbokulich --- I went through this from a user's perspective, so mostly just poking around the rendered viz, etc. The viz looks good, and I have no comments about the visualization params/signature! Code coverage looks good in abstract, but I would like to see some more discrete tests for all of the new utility functions --- these appear to be doing quite a bit of work, and it would be really nice to have that verified in the tests. Thanks, this will be really exciting to get in!

2017-09-08 19:09 UTC, thermokarst commented on q2_longitudinal/tests/test_longitudinal.py
> +
Can you add tests that check basic input/output testing of:

- `_add_sample_size_to_xtick_labels`
- `_control_chart_subplots`
- `_calculate_variability`
- `compare_variances`
- `_per_group_variance_comparison`
- `_multiple_tests_correction`
- `_control_chart`

Can you make sure that your tests reach into all of the branches in those functions? Thanks!

2017-09-11 16:53 UTC, nbokulich commented
thanks @thermokarst ! I have added additional unit tests covering the listed functions (with the exception of `_control_chart` and `_control_chart_subplots`, in which the internal variance-calculating function is already tested). Please take a look and let me know if there are any more that you think will be required.

2017-09-11 21:23 UTC, thermokarst requested changes
Thanks @nbokulich --- a few minor additions.

2017-09-11 21:23 UTC, thermokarst commented on q2_longitudinal/tests/test_longitudinal.py
> +    def test_multiple_tests_correction(self):
Can you hit the `ZeroDivisionError` [exception](https://github.com/qiime2/q2-longitudinal/pull/36/files?diff=unified#diff-2c51f01d10d89d64b9690e69ef63e479R485) in this test, or another `multiple tests_correction` test?

2017-09-11 21:23 UTC, thermokarst commented on q2_longitudinal/tests/test_longitudinal.py
> +    def test_per_group_variance_comparison(self):
Can you add a test where `baseline is not None`? That way we can test [all the branches](https://github.com/qiime2/q2-longitudinal/pull/36/files?diff=unified#diff-2c51f01d10d89d64b9690e69ef63e479R448) in this function.

2017-09-12 15:34 UTC, nbokulich commented
Thanks @thermokarst ! I have added tests for both cases.

2017-09-13 15:45 UTC, thermokarst approved these changes
Thanks for the tests @nbokulich! I reviewed for vis structure, test coverage, and general python review. Time to send this over to @gregcaporaso for functionality review! Thanks!

2017-09-18 15:35 UTC, thermokarst commented
LGTM, thanks @nbokulich. Passing this on to @gregcaporaso.

2017-09-20 14:07 UTC, gregcaporaso requested changes
Could you provide a description of what the dashed and dotted lines are in the control plots? That could possibly be a legend item in the plots. It looks like the solid line is the global mean, and the dotted and dashed lines are 2 and 3 standard deviations from the mean, respectively, but I'm not sure about that. 

It sounds like the code has been reviewed already and that you don't need me to do that. Is that correct?

2017-09-20 14:09 UTC, thermokarst commented
@gregcaporaso: the code has been reviewed from a plugin perspective, but the data integrity has not been verified by way of review ("do the visualizations convey the same message as the stats?", "are the stats here meaningful to the questions we are attempting to answer?", etc.).

2017-09-20 14:12 UTC, gregcaporaso commented
One more thought: Would it be worth adding a download link for the data used to generate these plots? Since we're not including any statistics, it could be useful to allow the user to get that data to do statistics on their own. If we did that, I think you'd want a file that looks something like:

```
delivery,month,studyid,shannon
vaginal,0,42,2.2
cesarian,0,43,3.0
...
```

2017-09-20 14:13 UTC, gregcaporaso commented
> the data integrity has not been verified by way of review

Thanks @thermokarst, I've reviewed the viz from that perspective, and just had the two comments above.

2017-09-20 14:17 UTC, thermokarst commented
@nbokulich: if you add a download link for the data, can you please provide that as a TSV at the very minimum? We are in the process of updating all visualizations to provide TSV as their primary download option (if they have a download option), and then if there are any other formats to download as, present those as secondary options (e.g. CSV, excel, etc.). Thanks!

2017-09-20 14:20 UTC, nbokulich commented
@gregcaporaso your intuition about the lines is correct. This is described in the plugin description [here](https://github.com/qiime2/q2-longitudinal/pull/36/files#diff-2fd4a61578bada3af3efd746842f8bc6R180) and the docs tutorial (currently pending in [this PR](https://github.com/qiime2/docs/pull/200))

Do you think it is necessary to add descriptive text to the viz if this is described in the plugin description (so appears when the user seeks `--help`) and tutorial?

Downloading data should be easy to add. @thermokarst no worries, tsv is my preferred format as well.

2017-09-20 14:24 UTC, gregcaporaso commented
> Do you think it is necessary to add descriptive text to the viz if this is described in the plugin description (so appears when the user seeks `--help`) and tutorial?

I think it'd be helpful, but not essential. Your call on this one @nbokulich.

2017-09-20 14:30 UTC, nbokulich commented
@gregcaporaso could I add the data download in a separate PR? I probably ought to do this for all actions (while others do generate stats, raw data download may be useful)

2017-09-20 14:35 UTC, gregcaporaso commented
Sure, that works. Want to create an issue for it and we can merge this one?

2017-09-20 14:37 UTC, nbokulich commented
> Sure, that works. Want to create an issue for it and we can merge this one?
@gregcaporaso : #47

2017-09-20 14:40 UTC, gregcaporaso approved these changes

2017-09-20 14:42 UTC, merged